#!/usr/bin/with-contenv bash

Green="\033[32m"
Font="\033[0m"
Red="\033[31m" 

# 更新trackers
if [ "$UT" == "true" ]; then
    wget -O /tmp/trackers_list.txt $TL
    Newtrackers="Bittorrent\TrackersList=$(awk '{if(!NF){next}}1' /tmp/trackers_list.txt | sed ':a;N;s/\n/\\n/g;ta')"
    Oldtrackers="$(grep TrackersList= /config/qBittorrent/config/qBittorrent.conf)"
    echo $Newtrackers >/tmp/Newtrackers.txt

    if [ -e "/tmp/trackers_list.txt" ]; then

        if [ "$Newtrackers" == "$Oldtrackers" ]; then
            echo -e "${Green}trackers文件一样,不需要更新。${Font}"
        else
            sed -i '/Bittorrent\\TrackersList=/r /tmp/Newtrackers.txt' /config/qBittorrent/config/qBittorrent.conf
            sed -i '1,/^Bittorrent\\TrackersList=.*/{//d;}' /config/qBittorrent/config/qBittorrent.conf
            echo -e "${Green}已更新trackers。${Font}"
        fi

        rm /tmp/trackers_list.txt
        rm /tmp/Newtrackers.txt

    else
        echo -e "${Red}更新文件未正确下载，更新未成功，请检查网络。${Font}"
    fi

else
    echo 未设定自动更新trackers。
fi