#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/config

if [[ -d /downloads ]]; then
    if [[ "$(stat -c '%U' /downloads)" != "abc" ]]; then
        chown -R abc:abc /downloads
    fi
fi